name: CI Pipeline

on:
    push:
        branches: ["main"]  # Run CI on pushes to main

    pull_request:
        branches: ["main"]  # Also run CI on PRs targeting main

jobs: 
    build-test: 
        runs-on: ubuntu-latest  # VM host for running CI steps
        steps: 
            # Step 1: Checkout code
            - name: Checkout code
              uses: actions/checkout@v4

            # Step 2: Set up Python
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
            
            # Step 3: Install dependencies & CI tools
            - name: Install dependencies
              run: | 
               python -m pip install --upgrade pip
               pip install -r requirements.txt
               pip install pylint pytest

            # Step 4: Lint all Python code
            - name: Lint Python code
              run: pylint **/*.py

            # Step 5: Lint Dockerfile
            - name: Lint Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                   dockerfile: Dockerfile

            # Step 6: Build Docker image
            - name: Build Docker image
              run: docker build -t hivebox:${GITHUB_SHA::7} .

            # Step 7: Run unit tests using pytest
            - name: Run unit tests
              run: python -m pytest tests/ -v

            # Step 8: Run container in background for testing
            - name: Run container
              run: docker run -d -p 8000:8000 hivebox:${GITHUB_SHA::7}

            # Step 9: Test /version endpoint
            - name: Test /version endpoint
              run: curl --fail http://localhost:8000/version | grep "0.0.1"
            
            # Step 10: Test /temperature endpoint
            - name: Test /temperature endpoint
              run: curl --fail http://localhost:8000/temperature | grep "average_temperature"

